[versions]
wiremock = "4.0.0-beta.28"
opensearch = "3.5.0"
wiremock-grpc-extension = "1.0.0-beta.5"
httpclient5 = "5.6"
slf4j = "2.0.17"
jboss-logging = "3.6.2.Final"
protobuf-java = "4.33.5"
grpc = "1.79.0"
javax-annotation = "1.3.2"
proto-google-common-protos = "2.65.0"
netty-codec-http = "4.2.9.Final"
junit-jupiter = "6.0.2"
junit-platform = "6.0.2"
shadow = "9.3.1"
proto-toolchain = "0.7.15"

# Plugins
axion-release = "1.21.1"
jib = "3.5.3"
protobuf-plugin = "0.9.6"
nmcp = "1.4.4"

[libraries]
wiremock-core = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
wiremock-grpc-extension-standalone = { module = "org.wiremock:wiremock-grpc-extension-standalone", version.ref = "wiremock-grpc-extension" }
wiremock-grpc-extension-core = { module = "org.wiremock:wiremock-grpc-extension", version.ref = "wiremock-grpc-extension" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jboss-logging = { module = "org.jboss.logging:jboss-logging", version.ref = "jboss-logging" }
protobuf-java-core = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf-java" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf-java" }
grpc-netty = { module = "io.grpc:grpc-netty", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-services = { module = "io.grpc:grpc-services", version.ref = "grpc" }
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation" }
proto-google-common-protos = { module = "com.google.api.grpc:proto-google-common-protos", version.ref = "proto-google-common-protos" }
netty-codec-http = { module = "io.netty:netty-codec-http", version.ref = "netty-codec-http" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
httpclient5 = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "httpclient5" }
opensearch-java = { module = "org.opensearch.client:opensearch-java", version.ref = "opensearch" }

[plugins]
axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-release" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
proto-toolchain = { id = "ai.pipestream.proto-toolchain", version.ref = "proto-toolchain" }